package com.example.borutoapp.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp

val PAGING_INDICATOR_WIDTH = 12.dp
val PAGING_INDICATOR_SPACING = 8.dp

val TOP_APP_BAR_HEIGHT = 56.dp
val HERO_ITEM_HEIGHT = 400.dp
val NAME_PLACEHOLDER_HEIGHT = 30.dp
val ABOUT_PLACEHOLDER_HEIGHT = 15.dp
val RATING_PLACEHOLDER_HEIGHT = 20.dp
val NETWORK_ERROR_ICON_HEIGHT = 120.dp

val INFO_ICON_SIZE = 32.dp

val MIN_SHEET_HEIGHT = 140.dp
val EXPANDED_RADIUS_LEVEL = 0.dp